[package]
name = "cityparquet-cli"
description = "CityParquet command-line tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cityparquet"
path = "src/main.rs"
doc = false

[dependencies]
cityparquet = { path = "../cityparquet" }
cityparquet-schema = { workspace = true }
clap = { workspace = true, features = ["derive"] }
arrow-array = { workspace = true }
parquet = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
cjseq = { workspace = true }
